version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_LOGIN: postgres
      POSTGRES_PASSWORD: 1998
    ports:
      - 5432:5432
    networks:
      - SocialNetwork
    command: ["postgres", "-c", "log_statement=all"]

  spring:
    image: web:latest
    depends_on:
      - db
    ports:
      - 8228:8228
    networks:
      - SocialNetwork
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/postgres?currentSchema=social_network_db

networks:
  SocialNetwork:
    driver: bridge